<?php
/**
 * DiagramFileApi
 * PHP version 5
 *
 * @category Class
 * @package  Aspose\Diagram\Cloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Aspose\Diagram\Cloud\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Aspose\Diagram\Cloud\ApiException;
use Aspose\Diagram\Cloud\Configuration;
use Aspose\Diagram\Cloud\HeaderSelector;
use Aspose\Diagram\Cloud\ObjectSerializer;

/**
 * DiagramFileApi Class Doc Comment
 *
 * @category Class
 * @package  Aspose\Diagram\Cloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DiagramFileApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation diagramFileGetDiagram
     *
     * Read document info or export.
     *
     * @param  string $name The document name. (required)
     * @param  string $format The exported file format. (optional)
     * @param  string $folder The document folder. (optional)
     * @param  string $storage storage name. (optional)
     *
     * @throws \Aspose\Diagram\Cloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function diagramFileGetDiagram($name, $format = null, $folder = null, $storage = null)
    {
        list($response) = $this->diagramFileGetDiagramWithHttpInfo($name, $format, $folder, $storage);
        return $response;
    }

    /**
     * Operation diagramFileGetDiagramWithHttpInfo
     *
     * Read document info or export.
     *
     * @param  string $name The document name. (required)
     * @param  string $format The exported file format. (optional)
     * @param  string $folder The document folder. (optional)
     * @param  string $storage storage name. (optional)
     *
     * @throws \Aspose\Diagram\Cloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function diagramFileGetDiagramWithHttpInfo($name, $format = null, $folder = null, $storage = null)
    {
        $returnType = '\SplFileObject';
        $request = $this->diagramFileGetDiagramRequest($name, $format, $folder, $storage);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation diagramFileGetDiagramAsync
     *
     * Read document info or export.
     *
     * @param  string $name The document name. (required)
     * @param  string $format The exported file format. (optional)
     * @param  string $folder The document folder. (optional)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function diagramFileGetDiagramAsync($name, $format = null, $folder = null, $storage = null)
    {
        return $this->diagramFileGetDiagramAsyncWithHttpInfo($name, $format, $folder, $storage)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation diagramFileGetDiagramAsyncWithHttpInfo
     *
     * Read document info or export.
     *
     * @param  string $name The document name. (required)
     * @param  string $format The exported file format. (optional)
     * @param  string $folder The document folder. (optional)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function diagramFileGetDiagramAsyncWithHttpInfo($name, $format = null, $folder = null, $storage = null)
    {
        $returnType = '\SplFileObject';
        $request = $this->diagramFileGetDiagramRequest($name, $format, $folder, $storage);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'diagramFileGetDiagram'
     *
     * @param  string $name The document name. (required)
     * @param  string $format The exported file format. (optional)
     * @param  string $folder The document folder. (optional)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function diagramFileGetDiagramRequest($name, $format = null, $folder = null, $storage = null)
    {
        // verify the required parameter 'name' is set
        if ($name === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling diagramFileGetDiagram'
            );
        }

        $resourcePath = '/diagram/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }
        // query params
        if ($folder !== null) {
            $queryParams['folder'] = ObjectSerializer::toQueryValue($folder);
        }
        // query params
        if ($storage !== null) {
            $queryParams['storage'] = ObjectSerializer::toQueryValue($storage);
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
            else if (gettype($httpBody) == 'array' && $headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if($this->config->getAccessToken()!==''){
            $defaultHeaders['Authorization']= 'Bearer ' . $this->config->getAccessToken();
        }
        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation diagramFilePostSaveAs
     *
     * Convert document and save result to storage.
     *
     * @param  string $name The document name. (required)
     * @param  \Aspose\Diagram\Cloud\Model\FileFormatRequest $format Save format. (optional)
     * @param  string $newfilename The new file name. (optional)
     * @param  string $folder The document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \Aspose\Diagram\Cloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Aspose\Diagram\Cloud\Model\SaveResponse
     */
    public function diagramFilePostSaveAs($name, $format = null, $newfilename = null, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        list($response) = $this->diagramFilePostSaveAsWithHttpInfo($name, $format, $newfilename, $folder, $is_overwrite, $storage);
        return $response;
    }

    /**
     * Operation diagramFilePostSaveAsWithHttpInfo
     *
     * Convert document and save result to storage.
     *
     * @param  string $name The document name. (required)
     * @param  \Aspose\Diagram\Cloud\Model\FileFormatRequest $format Save format. (optional)
     * @param  string $newfilename The new file name. (optional)
     * @param  string $folder The document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \Aspose\Diagram\Cloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Aspose\Diagram\Cloud\Model\SaveResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function diagramFilePostSaveAsWithHttpInfo($name, $format = null, $newfilename = null, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        $returnType = '\Aspose\Diagram\Cloud\Model\SaveResponse';
        $request = $this->diagramFilePostSaveAsRequest($name, $format, $newfilename, $folder, $is_overwrite, $storage);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aspose\Diagram\Cloud\Model\SaveResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation diagramFilePostSaveAsAsync
     *
     * Convert document and save result to storage.
     *
     * @param  string $name The document name. (required)
     * @param  \Aspose\Diagram\Cloud\Model\FileFormatRequest $format Save format. (optional)
     * @param  string $newfilename The new file name. (optional)
     * @param  string $folder The document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function diagramFilePostSaveAsAsync($name, $format = null, $newfilename = null, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        return $this->diagramFilePostSaveAsAsyncWithHttpInfo($name, $format, $newfilename, $folder, $is_overwrite, $storage)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation diagramFilePostSaveAsAsyncWithHttpInfo
     *
     * Convert document and save result to storage.
     *
     * @param  string $name The document name. (required)
     * @param  \Aspose\Diagram\Cloud\Model\FileFormatRequest $format Save format. (optional)
     * @param  string $newfilename The new file name. (optional)
     * @param  string $folder The document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function diagramFilePostSaveAsAsyncWithHttpInfo($name, $format = null, $newfilename = null, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        $returnType = '\Aspose\Diagram\Cloud\Model\SaveResponse';
        $request = $this->diagramFilePostSaveAsRequest($name, $format, $newfilename, $folder, $is_overwrite, $storage);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'diagramFilePostSaveAs'
     *
     * @param  string $name The document name. (required)
     * @param  \Aspose\Diagram\Cloud\Model\FileFormatRequest $format Save format. (optional)
     * @param  string $newfilename The new file name. (optional)
     * @param  string $folder The document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function diagramFilePostSaveAsRequest($name, $format = null, $newfilename = null, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        // verify the required parameter 'name' is set
        if ($name === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling diagramFilePostSaveAs'
            );
        }

        $resourcePath = '/diagram/{name}/SaveAs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($newfilename !== null) {
            $queryParams['newfilename'] = ObjectSerializer::toQueryValue($newfilename);
        }
        // query params
        if ($folder !== null) {
            $queryParams['folder'] = ObjectSerializer::toQueryValue($folder);
        }
        // query params
        if ($is_overwrite !== null) {
            $queryParams['IsOverwrite'] = ObjectSerializer::toQueryValue($is_overwrite);
        }
        // query params
        if ($storage !== null) {
            $queryParams['storage'] = ObjectSerializer::toQueryValue($storage);
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($format)) {
            $_tempBody = $format;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
            else if (gettype($httpBody) == 'array' && $headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if($this->config->getAccessToken()!==''){
            $defaultHeaders['Authorization']= 'Bearer ' . $this->config->getAccessToken();
        }
        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation diagramFilePutCreate
     *
     * Create new diagram and save result to storage.
     *
     * @param  string $name The new document name. (required)
     * @param  string $folder The new document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \Aspose\Diagram\Cloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Aspose\Diagram\Cloud\Model\SaaSposeResponse
     */
    public function diagramFilePutCreate($name, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        list($response) = $this->diagramFilePutCreateWithHttpInfo($name, $folder, $is_overwrite, $storage);
        return $response;
    }

    /**
     * Operation diagramFilePutCreateWithHttpInfo
     *
     * Create new diagram and save result to storage.
     *
     * @param  string $name The new document name. (required)
     * @param  string $folder The new document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \Aspose\Diagram\Cloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Aspose\Diagram\Cloud\Model\SaaSposeResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function diagramFilePutCreateWithHttpInfo($name, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        $returnType = '\Aspose\Diagram\Cloud\Model\SaaSposeResponse';
        $request = $this->diagramFilePutCreateRequest($name, $folder, $is_overwrite, $storage);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aspose\Diagram\Cloud\Model\SaaSposeResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation diagramFilePutCreateAsync
     *
     * Create new diagram and save result to storage.
     *
     * @param  string $name The new document name. (required)
     * @param  string $folder The new document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function diagramFilePutCreateAsync($name, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        return $this->diagramFilePutCreateAsyncWithHttpInfo($name, $folder, $is_overwrite, $storage)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation diagramFilePutCreateAsyncWithHttpInfo
     *
     * Create new diagram and save result to storage.
     *
     * @param  string $name The new document name. (required)
     * @param  string $folder The new document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function diagramFilePutCreateAsyncWithHttpInfo($name, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        $returnType = '\Aspose\Diagram\Cloud\Model\SaaSposeResponse';
        $request = $this->diagramFilePutCreateRequest($name, $folder, $is_overwrite, $storage);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'diagramFilePutCreate'
     *
     * @param  string $name The new document name. (required)
     * @param  string $folder The new document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function diagramFilePutCreateRequest($name, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        // verify the required parameter 'name' is set
        if ($name === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling diagramFilePutCreate'
            );
        }

        $resourcePath = '/diagram/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($folder !== null) {
            $queryParams['folder'] = ObjectSerializer::toQueryValue($folder);
        }
        // query params
        if ($is_overwrite !== null) {
            $queryParams['IsOverwrite'] = ObjectSerializer::toQueryValue($is_overwrite);
        }
        // query params
        if ($storage !== null) {
            $queryParams['storage'] = ObjectSerializer::toQueryValue($storage);
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
            else if (gettype($httpBody) == 'array' && $headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if($this->config->getAccessToken()!==''){
            $defaultHeaders['Authorization']= 'Bearer ' . $this->config->getAccessToken();
        }
        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation diagramFilePutUpload
     *
     * Upload file and save result to storage.
     *
     * @param  string $name The document name. (required)
     * @param  string $folder The document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \Aspose\Diagram\Cloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Aspose\Diagram\Cloud\Model\SaaSposeResponse
     */
    public function diagramFilePutUpload($localFilePath,$name, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        list($response) = $this->diagramFilePutUploadWithHttpInfo($localFilePath,$name, $folder, $is_overwrite, $storage);
        return $response;
    }

    /**
     * Operation diagramFilePutUploadWithHttpInfo
     *
     * Upload file and save result to storage.
     *
     * @param  string $name The document name. (required)
     * @param  string $folder The document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \Aspose\Diagram\Cloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Aspose\Diagram\Cloud\Model\SaaSposeResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function diagramFilePutUploadWithHttpInfo($localFilePath,$name, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        $returnType = '\Aspose\Diagram\Cloud\Model\SaaSposeResponse';
        $request = $this->diagramFilePutUploadRequest($localFilePath,$name, $folder, $is_overwrite, $storage);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aspose\Diagram\Cloud\Model\SaaSposeResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation diagramFilePutUploadAsync
     *
     * Upload file and save result to storage.
     *
     * @param  string $name The document name. (required)
     * @param  string $folder The document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function diagramFilePutUploadAsync($localFilePath,$name, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        return $this->diagramFilePutUploadAsyncWithHttpInfo($localFilePath,$name, $folder, $is_overwrite, $storage)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation diagramFilePutUploadAsyncWithHttpInfo
     *
     * Upload file and save result to storage.
     *
     * @param  string $name The document name. (required)
     * @param  string $folder The document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function diagramFilePutUploadAsyncWithHttpInfo($localFilePath,$name, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        $returnType = '\Aspose\Diagram\Cloud\Model\SaaSposeResponse';
        $request = $this->diagramFilePutUploadRequest($localFilePath,$name, $folder, $is_overwrite, $storage);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'diagramFilePutUpload'
     *
     * @param  string $name The document name. (required)
     * @param  string $folder The document folder. (optional)
     * @param  bool $is_overwrite If true overwrite the same name file.The default value is false. (optional, default to false)
     * @param  string $storage storage name. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function diagramFilePutUploadRequest($localFilePath,$name, $folder = null, $is_overwrite = 'false', $storage = null)
    {
        // verify the required parameter 'name' is set
        if ($name === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling diagramFilePutUpload'
            );
        }

        $resourcePath = '/diagram/{name}/upload';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($folder !== null) {
            $queryParams['folder'] = ObjectSerializer::toQueryValue($folder);
        }
        // query params
        if ($is_overwrite !== null) {
            $queryParams['IsOverwrite'] = ObjectSerializer::toQueryValue($is_overwrite);
        }
        // query params
        if ($storage !== null) {
            $queryParams['storage'] = ObjectSerializer::toQueryValue($storage);
        }
        if($localFilePath!=null)
        {

        }
        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
            else if (gettype($httpBody) == 'array' && $headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        $handle = fopen($localFilePath, "rb");
        $fsize = filesize($localFilePath);
        $httpBody = fread($handle, $fsize);
        $uploadname=basename($localFilePath);
        $defaultHeaders = [];
        $defaultHeaders['Content-Disposition'] =  "form-data; filename=\"" .$uploadname . "\"";

        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if($this->config->getAccessToken()!==''){
            $defaultHeaders['Authorization']= 'Bearer ' . $this->config->getAccessToken();
        }
        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
