<?php
/**
 * OAuthApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Aspose\Diagram\Cloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.Diagram Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Aspose\Diagram\Cloud;
require_once('TestBase.php');
use Aspose\Diagram\Cloud\Api\OAuthApi;
use PHPUnit\Framework\TestCase;
/**
 * OAuthApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aspose\Diagram\Cloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OAuthApiTest extends TestCase
{


    /**
     * Test case for oAuthPost
     *
     * Get Access token.
     *
     */
    public function testOAuthPost()
    {
        $oauthClient=new OAuthApi();
        $oauthClientConfig= $oauthClient->getConfig();
        $oauthClientConfig->setHost('https://api.aspose.cloud');
        $result  = $oauthClient->oAuthPost(TestBase::$grantType, TestBase::$clientId, TestBase::$clientSecret);
        $json = json_decode($result);
        $this->assertNotEmpty($json->access_token);
        TestBase::PrintDebugInfo("TestOAuthPost AccessToken:".$result);
    }
}
